# Default values for performanceTest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 'quay.io/jnirosha/jmeter-kafka-container'
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

kafkaProducer:
  bootstrapServer: 'https://abc.com:443'
  schemaRegistry: 'http://jude-registry-service:8080/apis/ccompat/v6'
  schemaRegistryCredentials: 'reg-admin:a1s2d3f4'
  transactionListTopic:
    topicName: test-client-tier-transaction-list
    numRecords: 1000000
    recordSize: 160
  accountTopic:
    topicName: test-client-tier-account
    numRecords: 1000000
    recordSize: 128

jmeter:
  sleepTime: 30
  loopCount: 5

annotations: {}
nameOverride: ""
fullnameOverride: ""
